### PR TITLE
Fix return arguments which htttp.target is status|header being added to swagger return body

### LINKED ISSUE #130: Incorrect swagger.json generated for return values having a http.target set to header or status
# Description/Steps to reproduce
Step to reproduce:
The example from loopback doc.
https://loopback.io/doc/en/lb3/Remote-methods.html#argument-descriptions
```js
module.exports = function(MyModel) {
  MyModel.download = function(cb) {
    // getTheStreamBody() can be implemented by calling http.request() or fs.readFile() for example
    getTheStreamBody(function(err, stream) {
      if (err) return cb(err);
      // stream can be any of: string, buffer, ReadableStream (e.g. http.IncomingMessage)
      cb(null, stream, 'application/octet-stream');
    });
  };

  MyModel.remoteMethod('download', {
    returns: [
      {arg: 'body', type: 'file', root: true},
      {arg: 'Content-Type', type: 'string', http: { target: 'header' }}
    ]
  });
};
```

# Cause in source code
Comparing the `convertReturnsToSwagger` function [source code](https://sourcegraph.com/github.com/strongloop/loopback-swagger/-/blob/lib/specgen/route-helper.js#L122-155) to `convertAcceptsToSwagger` function [source code](https://sourcegraph.com/github.com/strongloop/loopback-swagger/-/blob/lib/specgen/route-helper.js#L61-87)

The step of filtering out arguments pointing different http items is missing.

# Fix suggestion

Filter out the arguments having `http.target` set to `header|status` in the `convertReturnsToSwagger` function.

### PR DESCRIPTION
**Pull request by yshing**
### Description
Fix #130 
Filter out the return arguments if the `http.target` is set to `status|header` when converting returns to swagger.

#### Related issues
- connect to #130 

- connect to <link_to_referenced_issue>

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

File: lib/specgen/route-helper.js [hunk 1]
```diff
@@ -107,6 +107,12 @@ var routeHelper = module.exports = {
       return undefined;
     }
 
+    // Filter out parameters that are generated from the incoming request,
+    var ignoredHttpTargets = new Set(['header', 'status']);
+    routeReturns = routeReturns.filter(function(arg) {
+      return !arg.http || !arg.http.target || !ignoredHttpTargets.has(arg.http.target);
```
Comment (STRML) [inline lib/specgen/route-helper.js]: This boolean logic is pretty unclear, and we can't rely on `Set`, so how about:
```js
var ignoredHttpTargets = ['header', 'status'];
routeReturns = routeReturns.filter(function(arg) {
  return ignoredHttpTargets.indexOf(arg.http && arg.http.target) === -1;
});
```

Comment (yshing) [reply lib/specgen/route-helper.js]: That would create a undocumented behaviour where the arguments having `http` set to 'header' or 'status' String being filtered out.

And this kind of thing would be very hard to debug.

Properly type guarding it is essential.

And 

`Set` is added in node.js 4.0. Is safe for 2.x and 3.x

Comment (yshing) [reply lib/specgen/route-helper.js]: However the `!arg.http.target ||` is not 100% necessary, maybe removing it make the logic more clear?

Comment (STRML) [reply lib/specgen/route-helper.js]: Sure. Then use a ternary (`arg.http ? arg.http.target : null`). But the project style is very clearly ES5 so there's no reason to use a Set here.

File: lib/specgen/route-helper.js [hunk 2]
```diff
@@ -107,6 +107,12 @@ var routeHelper = module.exports = {
       return undefined;
     }
 
+    // Filter out parameters that are generated from the incoming request,
```
Comment (bajtos) [inline lib/specgen/route-helper.js]: Please fix this comment - output parameters are not generated from the incoming request!

File: lib/specgen/route-helper.js (hunk 1 above)
Comment (bajtos) [reply lib/specgen/route-helper.js]: How about the following:

```ts
const target = arg.http && arg.http.target;
return target !== 'header' && target !== 'status';
```

**Comment by bajtos** [comment]
@STRML does the patch LGTY now? Should I wait for your review, or can we proceed with landing?

**Comment by STRML** [comment]
LGTM

**Comment by bajtos** [comment]
Landed, thank you @yshing for the contribution ❤️ 

I have published the fix in `loopback-swagger@5.7.2`.
