### PR TITLE
specgen: emit correct non-root return types

### LINKED ISSUE #126: Model types are converted to "object" unless they are set as root
# Description/Steps to reproduce
When a model is registered with the loopback type registry and it is referenced as a return type in a remote method it is being converted to a "object" model rather than being set as a reference definition.

# Link to reproduction sandbox
[loopback-model-sandbox](https://github.com/Danwakeem/loopback-model-sandbox)

> See the `GET /sample/fail/{id}` endpoint to view the error

# Expected result

```
{
  "test": [
    {
      "foo": "string",
      "id": 0
    }
  ]
}
```

## Actual result
```
{
  "test": [
    {}
  ]
}
```

# Additional information
I noticed someone opened this issue here strongloop/loopback#2447 when the fix should be in this repository.

### PR DESCRIPTION
**Pull request by Danwakeem**
### Description
Fixed the issue where return types not set as a root property were not being set as loopback model references.

#### Related issues

- fix #126 
- fix strongloop/loopback#2447

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@Danwakeem thank you for the pull request. The changes looks reasonable on the first quick look, I'll try to find time to review them in detail in the next few days.

**Comment by bajtos** [comment]
@slnode ok to test

File: lib/specgen/route-helper.js [hunk 1]
```diff
@@ -138,7 +138,8 @@ var routeHelper = module.exports = {
       } else {
         debug('Swagger: temporarily using `object` instead of unknown ' +
           'type %j found in route %j', itemIdlType, route);
```
Comment (bajtos) [inline lib/specgen/route-helper.js]: Please change this debug statement - it should be printed only when `itemIdlType` was not found in the typeRegistry and the generic object type was used.

File: test/specgen/route-helper.test.js [hunk 2]
```diff
@@ -28,7 +28,7 @@ describe('route-helper', function() {
         {name: 'unknownModel', type: 'UnknownModel'},
         {name: 'requiredStr', type: String, required: true},
       ],
-    });
+    }, null, {name: TestModel.definition.name, definition: TestModel.definition});
```
Comment (bajtos) [inline test/specgen/route-helper.test.js]: One argument per line please, see https://loopback.io/doc/en/contrib/style-guide-es6.html

File: test/specgen/route-helper.test.js [hunk 3]
```diff
@@ -195,6 +195,54 @@ describe('route-helper', function() {
...
+      });
+  });
+
+  it('correctly converts registered non root return types', function() {
+    var customType = loopback.createModel('customType', {foo: String});
+    var doc = createAPIDoc({
+      returns: [
+        {arg: 'data', type: ['customType']},
+      ],
+    }, null,
```
Comment (bajtos) [inline test/specgen/route-helper.test.js]: One arg per line please.

File: test/specgen/route-helper.test.js [hunk 4]
```diff
@@ -484,12 +532,15 @@ describe('route-helper', function() {
 });
 
 // Easy wrapper around createRoute
-function createAPIDoc(def, classDef) {
+function createAPIDoc(def, classDef, type) {
```
Comment (bajtos) [inline test/specgen/route-helper.test.js]: To be honest, I find `type` argument confusing when reading test code. At minimum, I would expect `createAPIDoc` to accept arbitrary number of types.

Have you considered accepting a type registry instead of name/definition object? If we accept a registry instance, then tests using this method can use other APIs besides `registerLoopbackType` to set up the type registry and also register more than a single type.

Intended usage:

```js

const remotingSpec = {
  // ...
};

const typeRegistry = new TypeRegistry();
typeRegistry.registerLoopbackType(TestModel.definition.name, TestModel.definition);

const entry = createAPIDoc(remotingSpec, null, typeRegistry);
```

File: test/specgen/route-helper.test.js (hunk 2 above)
Comment (Danwakeem) [reply test/specgen/route-helper.test.js]: It is strange that that was not caught by the linter. Should I take a look at adding a PR for this in the [strongloop/eslint-config-loopback](https://github.com/strongloop/eslint-config-loopback) project?

**Comment by Danwakeem** [comment]
@bajtos No problem! I was able to make the changes you suggested.

**Comment by Danwakeem** [comment]
Just so it is easier to see here is my comment on the linter since it is auto collapsed due to my last commit :)

> It is strange that that was not caught by the linter. I believe I see what needs to be changed to catch these issue with the linter. Should I take a look at adding a PR for this in the [strongloop/eslint-config-loopback](https://github.com/strongloop/eslint-config-loopback) project or just add the lint changes to the `.eslintrc` file?

File: test/specgen/route-helper.test.js (hunk 2 above)
Comment (bajtos) [reply test/specgen/route-helper.test.js]: > Should I take a look at adding a PR for this in the strongloop/eslint-config-loopback project or just add the lint changes to the .eslintrc file?

Updating `strongloop/eslint-config-loopback` would be better, as it will enforce this rule in all loopback projects once they update to the new version of the configuration.

I am not sure if eslint has a rule to enforce argument formatting. Don't worry if you don't find any. I think a much better solution is to switch to `prettier` to handle consistent code formatting, but that's probably not worth the effort to be honest.

**Comment by bajtos** [comment]
> Should I take a look at adding a PR for this in the strongloop/eslint-config-loopback project or just add the lint changes to the .eslintrc file?

Updating `strongloop/eslint-config-loopback` would be better, as it will enforce this rule in all loopback projects once they update to the new version of the configuration.

I am not sure if eslint has a rule to enforce argument formatting. Don't worry if you don't find any. I think a much better solution is to switch to `prettier` to handle consistent code formatting, but that's probably not worth the effort to be honest.

**Comment by bajtos** [comment]
LGTM. I made few more code cleanups in 3aa9c78 and squashed all commits into a single one. Let's wait for CI results before merging.

**Comment by bajtos** [comment]
Landed 🎉 Tthank you for the contribution ❤️ 

Because you send the PR from your `master` branch, you will need a bit of cleanup work on your side to make your `master` branch up to date with our `master` branch (the upstream).

1. If you don't have strongloop's repository configured as an upstream `remote` yet:
    ```
    $ git remote add upstream https://github.com/strongloop/loopback
    ```

2. Fetch the latest updates from `upstream`:
    ```
    $ git fetch upstream
    ```

3. Hard-reset your master to `upstream`:
    ```
    $ git checkout master
    $ git reset --hard upstream/master
    ```

4. Force-push your changes back to GitHub
    ```
    $ git push -f
    ```

In the future, please create a new feature branch for each pull request. I recommend the following guide for step-by-step instructions showing the recommended contribution workflow: https://www.nearform.com/blog/first-time-with-open-source/

**Comment by Danwakeem** [comment]
@bajtos Awesome, thanks for the tips! I will be sure to do that on future PR :)
